### ISSUE TITLE
[Feature Request] Subscription Emulation using RSS

### ISSUE THREAD

**Issue by aphirst** [ram-on/SkyTube#1]
Hi there, just found about this project, and think it's pretty interesting.

I'll just get straight to the point. I have no Google account but I "subscribe" to YouTube channels I like using the fact that each channel also provides an RSS feed for their posted videos. So I just have a big load of RSS feeds that I have synchronising and I stay up to date. It occurs to me that these might be useful too, to be able to "emulate" having channel subscriptions.

**Comment by ram-on** [comment]
Thx for your support.

Channel bookmarking will be implemented for the next release (version 2.0)

Regarding the RSS feed:
YouTube works this way:
* A new video is uploaded to a channel
* User gets a notification.
* For each video uploaded, the notification counter will increase until the users starts watching the videos - in that case the video counter will decrement by one

My point is that this can be implemented, however in order to do that the app needs to keep a history of all videos watched by the user.

Hence this will, most probably, be added in version 3.0.

**Comment by ram-on** [comment]
Done.
