### ISSUE TITLE
Feature request: Pre-downloading videos

### ISSUE THREAD

**Issue by gzsombor** [ram-on/SkyTube#123]
Sometimes I would like watch Youtube videos, when there is little, or no connectivity - it would be nice, if SkyTube could  
* download videos to show later - videos which are bookmarked, or marked as 'watch later'
* download new videos from a specific channel automatically

What do you think, this request is technically and legally feasible? I don't know, what are the rules using Youtube. Have you planned similar thing?

**Comment by ram-on** [comment]
I'm planning to have the download video/music feature - this will cover your first point.

Watch later will be implemented however i don't think it will download the video automatically.

**Comment by atomjack** [comment]
@ram-on I've just added a branch that fulfills this request. Would love to hear your thoughts. Here are my notes:

1) Each video cell (in the video grid) now has a download button, directly to the left of the video options button. Clicking the button will initiate the download, and the button will animate to show that the video is downloading (and then it will disappear once the download is finished).

2) I've added a 5th tab to the View Pager, for Downloads (and also added it to the default tab options). It works similarly to the Subscribed/Bookmarks feeds, but on a separate database for downloaded videos.

3) It uses the Android builtin DownloadManager to do the actual downloads. Each GridViewHolder will register a BroadcastReceiver (only upon download link click) to receive the Broadcast from the DownloadManager that the video is completed downloading. It then saves the URI to the local file in the DownloadedVideosTable (and unregisters the BroadcastReceiver).

4) I've implemented listeners for the DownloadedVideosDb, similar to how it's done for Bookmarks. All 5 fragments will be listeners, though, since any video can be downloaded/deleted, and if the video is on any of the other tabs, they should be refreshed to reflect the change (mainly showing/hiding the download button). However, the refresh won't happen for the currently selected Fragment, since the video's GridViewHolder will update itself to reflect the change (hiding/showing the download button).

5) I've moved the code that gets the desired stream for a Video into YouTubeVideo.java, since it's really only relevant for that class. It uses an interface to return the found stream. 

6) One thing I've noticed is that getting the desired stream can take a little while (more than a few seconds, sometimes), and of course only then can the download actually proceed. Not sure of a way around this.

I've tested this by downloading a video and then turning Airplane mode on, and it works :)

**Comment by ram-on** [comment]
@atomjack I agree with this approach.  The only reservation I have is about the download button as I was more thinking about adding it into the three-dot-menu.

**Comment by atomjack** [comment]
@ram-on Gotcha. Should I go ahead and remove the download button and add an option to the options menu? Or do you wanna think on it some more.

**Comment by ram-on** [comment]
Is it available in one of your branches?

**Comment by atomjack** [comment]
Yeah, https://github.com/atomjack/SkyTube/tree/offline-videos

**Comment by ram-on** [comment]
Hey Chris, I've just tested it.  Looks great!  The following are issues i've noted:

* Yeah its better if you remove the download icon from the grid -- just add it as an option to the video's menu.
* The download option should also be available via the YouTube player's (activity) menu (i.e. while playing the video).
* When a downloaded video is deleted, the video is not removed from the Downloads tab.
* If the app fails to download a video (e.g. "The Talk - Hilary Duff Dishes on Boyfriend Matthew Koma: 'third times a charm'" -- currently listed in Trending), the video will still be added to the Downloads tab after another video is successfully downloaded.
* If a user deletes a previously downloaded video using Android's file manager, then upon SkyTube relaunching, the video should be automatically deleted from the download's database and remove from the download feed.

**Comment by atomjack** [comment]
@ram-on Awesome. For the YouTube Player's menu, for a downloaded video, should there be an option to delete the video? The thing is, it'll be playing the local file video at the time, so either the video would have to stop playing, then delete, or else it would have to get deleted after playback stopped.

**Comment by atomjack** [comment]
Oh yeah, one thing I also meant to add was an option the user could set to allow downloads while on Mobile. What do you think? If we do have that option, and they set it to not allow downloads on mobile, should it hide the download option, or display a message when they click on it instead?

**Comment by ram-on** [comment]
> For the YouTube Player's menu, for a downloaded video, should there be an option to delete the video? The thing is, it'll be playing the local file video at the time, so either the video would have to stop playing, then delete, or else it would have to get deleted after playback stopped.

Good point.  No that option should not be available when playing videos.

> Oh yeah, one thing I also meant to add was an option the user could set to allow downloads while on Mobile. What do you think? If we do have that option, and they set it to not allow downloads on mobile, should it hide the download option, or display a message when they click on it instead?

Good idea.  Pls proceed.

**Comment by gzsombor** [comment]
Wow, it looks awesome ! 
Putting the download action under the menu makes it more consistent, but unfortunately using menus are not very touch friendly.

**Comment by atomjack** [comment]
Thanks @gzsombor !!

@ram-on, since I'm removing the download button, there's no need for the other Fragments to be updated when then DownloadsDB gets updated, so I'll be changing it so that only the DownloadedVideosFragment is a listener.

**Comment by atomjack** [comment]
@ram-on Also, for the allow downloads on mobile option, which did you prefer, hide the download option, or show a Toast when it's clicked?

**Comment by ram-on** [comment]
> since I'm removing the download button, there's no need for the other Fragments to be updated when then DownloadsDB gets updated, so I'll be changing it so that only the DownloadedVideosFragment is a listener.

Great -- less complexity.

> Also, for the allow downloads on mobile option, which did you prefer, hide the download option, or show a Toast when it's clicked?

The default option behavior be to hide the download option when using mobile plan.  However it would be nice if an option would be inserted in the preferences which allows the user to download videos irrespective if he is using wifi or 4g.

**Comment by atomjack** [comment]
> If a user deletes a previously downloaded video using Android's file manager, then upon SkyTube relaunching, the video should be automatically deleted from the download's database and remove from the download feed.

Ok, I'll add that. I'll also have it display a Toast if the video file becomes missing after the app has already launched, as well as remove it from the list.

> The default option behavior be to hide the download option when using mobile plan. However it would be nice if an option would be inserted in the preferences which allows the user to download videos irrespective if he is using wifi or 4g.

Yep, I've added a CheckboxPreference to Others that allows downloads on mobile. If this is unchecked (I'm assuming it should be unchecked by default), and the user is not connected via WiFi, the download option is hidden. This necessitated the addition of the `android.permission.ACCESS_NETWORK_STATE` permission, btw.

I'll have an updated commit shortly.

**Comment by atomjack** [comment]
@ram-on Just pushed an update to the`offline-videos` branch, contains just about all that stuff (see the commit message). I was able to download that "The Talk" video just fine, so I wasn't able to reproduce that. I'll doublecheck the code though.

**Comment by ram-on** [comment]
@gzsombor Chris just implemented your FR -- refer to #208.  It will be available in the next release.

**Comment by gzsombor** [comment]
Awesome, thanks! Happy new year ! :smile:
