### ISSUE TITLE
Regions filter not working

### ISSUE THREAD

**Issue by KuzeydekiBuyucu** [ram-on/SkyTube#146]
I prefered turkey region and turkish language but most popular videos still same why it does not work

**Comment by ram-on** [comment]
Hi, the prefered region works for the Featured Videos.  The Preferred language is a filter for the Most Popular videos however it will not filter each and every video due to the fact that not every video is tagged with a language (only some do).  Hope this helps.

I'm closing this for now.  Feel free to reopen it should you require further clarifications.
