### ISSUE TITLE
new version?

### ISSUE THREAD

**Issue by juanserj45** [ram-on/SkyTube#166]
Hey sorry for ask this but when the new update with the subscribers import come? I'm waiting that to use more daily this great app. Thz for your work

**Comment by ram-on** [comment]
Hi.  A new version will probably roll out this weekend provided that no major bugs are noted.

**Comment by juanserj45** [comment]
Do you need beta tester?

**Comment by ram-on** [comment]
@juanserj45 Please find the Beta here:

[SkyTube-Extra-2.69Beta.apk.zip](https://github.com/ram-on/SkyTube/files/1396153/SkyTube-Extra-2.69Beta.apk.zip)

Feel free to report any issues identified.

**Comment by mcitew** [comment]
Notice this version allows "limited" capability to scroll the video items using the TV remote down arrow, 

However, on the screen, there is no cursor feedback/indication that which video item/cell is selected, users have no idea which video item is selected, and hitting the "OK" button on the remote has no effect in selecting any video item. 

While it can be scrolled down, it can't be completely scrolled up, it will scroll until one point and then it will jump back to one of the 4 tab layout selection instead of showing the full view of the first row of the cells.

**Comment by juanserj45** [comment]
i have some randoms FC when was searching videos but the most annoying it is when you unsubscribed to a channel the channel list is clean and you need to reset the app to see again the channels. 
Other thing it is weird when is loading the videos the channels it take too long in 0%.
I was expecting the implementation of immersive mode. 
Other think than you need to say that the archive you download from youtube is not a XML you need to add the archive type to the program to see it. 

Sorry for my bad English thx for the hard work

**Comment by ram-on** [comment]
Thanks for reporting issues with this beta.

@mcitew Noted.  Currently Android TV is not supported - however it will be supported in the near future.

@juanserj45 

> it is when you unsubscribed to a channel the channel list is clean and you need to reset the app to see again the channels.

This above mentioned bug has just been fixed (32207a8ec1d18690924688e10feeca5e680b0439)

**Comment by ram-on** [comment]
@mcitew and @juanserj45 

Please find another beta for testing.

[SkyTube-Extra-2.691Beta.apk.zip](https://github.com/ram-on/SkyTube/files/1408564/SkyTube-Extra-2.691Beta.apk.zip)

**Comment by ram-on** [comment]
@juanserj45 I've just released an updated (version 2.70) which supports YouTube subscriptions importation.
