### ISSUE TITLE
old version

### ISSUE THREAD

**Issue by aykutkaraca** [ram-on/SkyTube#177]
Hi Ramon,

I used one of your old versions (dont know how to look, where does it say, in graddle file?) and I modified it for creating Kids Tube (free with no ads). It is not possible that I update my app with your updates now as I changed things. In my version sometimes the videos dont show. It either keeps showing blank screed with turning icon or it starts with sound but doesnt show the image. Where is the bug? I am sure you already solved it in your version. Thanks in advance!!!!

**Comment by atomjack** [comment]
What I suggest you do is merge the master branch (from ram-on/SkyTube) onto the branch you made where you changed things. I'm assuming you forked the repository, and then did your work on that fork. You'll of course need to add a remote that points to this repository (call it upstream). Here's instruction on how to add the remote: https://help.github.com/articles/configuring-a-remote-for-a-fork/

And then here's instructions on how to merge the upstream changes (i.e. the changes that have been done to the master branch on here since you forked): https://help.github.com/articles/syncing-a-fork/

I suggest you make a local backup branch of the changes you made, just to have it, before you try to merge. When you merge, most likely there will be conflicts, which you will have to solve in order to get it to compile. But that's the best way to do it.

Reply with more details on how you did your changes (not the changes themselves, but whether or not you actually forked the repository, did you do your changes on a separate branch or on master (of your fork), etc)

**Comment by ram-on** [comment]
@aykutkaraca You need to perform a fork as noted by @atomjack.

It is very important that your app's source code is made available to the public as otherwise it would be breaching the SkyTube's license (GPLv3).
