### ISSUE TITLE
Cant remove (deleted) channel from subscription list

### ISSUE THREAD

**Issue by ByteTemplar** [ram-on/SkyTube#189]
So, I have this channel subscribed that was deleted by Youtube (or removed by owner) and now its just blank icon without name on the list (left bar). If I select it, random videos are listed and cant unsubscribe either (shows subscribe button). If I click the subscribe button, error pops up "Unable to (un)subscribe the channel (id=null).

Dont know how to handle these things, but would like an option to remove it somehow. Maybe click and hold for option to remove from list?

If I use browser to open that channel, it still shows a page but has warning that channel is removed, so channel is kind of there but unavailable, probably why Skytube shows it.

**Comment by atomjack** [comment]
@ByteTemplar I could take a crack at fixing this, but in order to recreate it I'd need to be subscribed to a channel that is no longer available. Can you do an export of your SkyTube settings (which would include all your subscriptions, including the one that was deleted) and then leave a link to the xml file here, or email it to me? (atomjack at gmail)

**Comment by ram-on** [comment]
Fixed as per 6d8b4499f5c855e81f687fd5539ace839d14b7c4

**Comment by ByteTemplar** [comment]
Finally had time to reply at atomjack and got an email its fixed by the dev! Nicely done!

Just wanted to thank you :)
