### ISSUE TITLE
Enhancement: push notifications and auto-refresh

### ISSUE THREAD

**Issue by stemy2** [ram-on/SkyTube#191]
Hello,

To see new video, i'm forced to open the app and swipe down regularly. It would be nice to have a notification at every new video as in the official YT app.

Thanks.

**Comment by atomjack** [comment]
I'm working on this right now. @ram-on, can I get your input on a few things?

1) It'll be using the Alarm Manager in order to trigger checking for new videos from subscribed channels. In Preferences -> Other, there will be a new option for "Feed Auto Notification", where you can select how often it should check for new videos from subscribed channels. The first option will be off, followed by 1 or more options, like every X hours. What do you think these options should be? 6, 12, 24? We probably don't want it happening too often, so as to not waste too many API requests.

2) When new videos are found, it will display a Notification. I was thinking, if only one new video happens to be found (out of all subscribed channels), the notification could display the Channel & Video title, along with a thumbnail for the video (and something like "New video from <Channel Name>: <Video Name>)". If more than one is found, a generic message saying "X new videos found from subscribed channels" (or something to that effect, I'm open to suggestions) instead.

3) When some hour option is selected (from whatever options we decide on), should it trigger a check for new videos right away? Or X hours (whatever option was selected) from now, for the first check (and then every X hours after that)? I'm thinking the latter. e.g. I select every 6 hours, so the next check will be in 6 hours from now, followed by another 6 from then, etc.

4) Supposing the latter, and the options are 6, 12, and 24 hours, let's say I set it to 6 hours, and some time later (a day, whatever), I go in to change it, and it happens that the next time it is supposed to check (at every 6 hours) is in 4 hours from now. If I change it to 12, should the next automatic check be in 12 hours from now, or 8 (12 - 4 = 8)?

Also, I don't think getting a notification for every new video will be practical, since we won't be able to use push notifications, and having it check too often will eat up the user's battery as well as API requests.

@ram-on, what do you think? @stemy2 I'd appreciate your thoughts as well.

**Comment by ram-on** [comment]
Hello @atomjack 

1. I agree with 6, 12, 24 hours
2. I would keep it simple and always display a notification saying something like "X new videos uploaded from subscribed channels".  Once the user taps the notification, the app will open the feed tab as you suggested.
3. I prefer that such check is carried out X hours after the option is selected (in order to conserve the api quota)
4. If the user changes the settings, the check will be carried out X hours later.  I don't see that as a problem to be honest.

**Comment by atomjack** [comment]
@ram-on I just pushed up a branch with this. I've followed your 4 points above.

Some notes:

1) I renamed SubscriptionsFragmentListener to GetSubscriptionVideosTaskListener, since it's really mainly relevant to that task. Seemed to make more sense to me. I also changed it to pass an ArrayList of the videos that were found (for a particular channel), instead of just the number. I originally did this so that the Notification could display information for the video (if only one was found), but we're not doing that, but I figured we can leave it in in case it's ever needed.

2) There's a Service (FeedUpdaterService) that does the actual check for new videos. There are also two BroadcastReceivers - one that the AlarmManager sends a message to in order to tell the Service to do the check, and another that happens when the device boots up - this is so that when the user reboots their device, the Service will get fired X hours from then, depending on what the user chose in Preferences (and of course if they chose "Off", it doesn't set up the Alarm).

3) I've added a notification icon which you can see in the drawable folders, called ic_notification_icon.png.

4) If you'd like to test it out without having to wait 6 hours for it to trigger, update the values in the feed_notification_values string array (in strings_preferences.xml) and set it to something low. I'll note that the minimum amount of time before it will trigger is one minute. So, if you set it to like 1000 milliseconds, it will still take at least a minute for it to trigger. You can also update FeedUpdaterService.onAllChannelVideosFetched and change the if statement (newVideosFetched.size() > 0) to always pass, so you can see and test the notification without having to wait until your subscriptions have new videos (it will just say 0 new videos found).

I set it to 6 hours yesterday afternoon, and sure enough, 6 hours later I got the notification that new videos had been found, and I woke up this morning to another notification that more new videos were found.

**Comment by ram-on** [comment]
Hello @atomjack.  I've tested it out -- I've changed the refresh time to 2 minutes.  When I set such feed refesh time via preferences, I've noted that GetSubscriptionVideosTask gets called periodically -- however when I restarted the app, GetSubscriptionVideosTask does not get called.  Can you look into it?

**Comment by atomjack** [comment]
Hey @ram-on, nice catch! I've added a commit to that branch which fixes that problem.

**Comment by ram-on** [comment]
Implemented as per PR #191
