### ISSUE TITLE
chomecast

### ISSUE THREAD

**Issue by ghost** [ram-on/SkyTube#22]
will you support chromecasts in the future? or will that add APIs that would hurt the openness of the project?

**Comment by theScrabi** [comment]
Someone wrote Chromecast support for NewPipe. Maybe this code could be adopted for skytube.

**Comment by ram-on** [comment]
Someone is currently writing a module to support chromecast.  Unfortunately I do not own such device.

**Comment by atomjack** [comment]
I'm working on it right now. I really don't have an ETA though, it's just when I can get some time to spend on it. It will be part of the version that lets you use the official YouTube player.

And since it has to use Google API's, we can also include support for logging in via Google in order to pull Subscriptions from your YouTube account, but that will be down the road.

**Comment by KeizerDev** [comment]
>@theScrabi Someone wrote Chromecast support for NewPipe. Maybe this code could be adopted for skytube.

That was me, lol, I would love to implement it here too but if @atomjack already started I will just leave it to him. If you (@atomjack) have a branch are you're working on I would like to check it out 😃

**Comment by atomjack** [comment]
Yeah, I'm almost done with the initial branch. Just with minimal support, as far as UI goes - just a small bar that appears in the bottom of the app when you start playing something to Chromecast, with control buttons on it (as well as notifications etc). I have to work on a few things but it should be ready soon, now that my other PR's are all merged :)

Here's a screenshot: http://i.imgur.com/3v32MRr.png

I also have a branch building on this that has the start to a full screen UI that you can tap or slide up (similar to how the Netflix app operates when you use it with Chromecast), but that will require some more work. I'll keep you guys posted.

**Comment by theScrabi** [comment]
@ram-on @KeizerDev but remember if you include google play service lib you will lose fdroid support.

**Comment by atomjack** [comment]
@theScrabi There are two flavors of Skytube - the OSS version and the Extra version (which isn't 100% open source). The Extra version already includes the option to use the official YouTube Player, instead of the internal one, so Chromecast support will only be in the Extra version.

**Comment by theScrabi** [comment]
Alright I see :)

**Comment by atomjack** [comment]
I just pushed up a new branch to my fork, that adds preliminary Chromecast support. You can check it out [here](https://github.com/atomjack/SkyTube/tree/chromecast). Some notes:

1. There is no full screen UI/controller yet, just a small panel on the bottom of the screen when a video is playing to a Chromecast. You can rewind 10 seconds, pause/resume, stop, and fast forward 30 seconds from this panel. I do have another branch that I have added a full screen UI/controller to, but it is not done yet - it only has a big thumbnail + the aforementioned controls on it, and I figure it should also have a place to view comments. If anyone would like to help me with designing the UI for it, please email me (atomjack at gmail).
2. If you are casting a video and tap on another video (even the same video) in the Grid, the new video you tapped on will load and start playing, interrupting the currently playing video. I figure eventually when we add playlist/queue support, tapping on a video while connected to a Chromecast will give you the option to add that video to a playlist/the queue, or just start playing the video right away.
3. You have to change the Build Variant to "Extra", in order to be able to cast to a Chromecast. This variant contains the Google Play Services libraries that are required for Chromcast support. 
4. I would suggest building the ExtraRelease variant, not ExtraDebug, as the Debug version uses the Chromecast Frontend (HTML5) app on my local Linux box, while the Release version uses it hosted on S3. The Debug version IS accessible from the internet, but if my box is down or my internet connection goes out, it won't work. 

@KeizerDev please check it out and let me know what you think :)

**Comment by ram-on** [comment]
I'll check it out.  @KeizerDev Your feedback will be appreciated

**Comment by atomjack** [comment]
A beta of Skytube Extra variant (which contains non-open source Google Play Services, as opposed to the regular OSS verison) is ready for people to test, if you'd like to. You can grab the apk here: https://drive.google.com/open?id=1XlWQegfHzwWW0r0IJvBtgJ7_uSvgCu0a

Please let me know if you run into any trouble or have any comments!

**Comment by realdmitchell** [comment]
which branch is this? master? Thx

**Comment by atomjack** [comment]
That branch is a bit behind master, I'll be trying to rebase it today.

**Comment by realdmitchell** [comment]
@ram-on will try tonight and let you know. Thx again.

**Comment by atomjack** [comment]
@realdmitchell I've rebased that branch so it's up to date with the latest changes on master. If you've already pulled the branch down, delete your local and pull it down again.

**Comment by aancel** [comment]
I'm also interested in chromecast support.
@atomjack Do you intend to open a PR with the modifications you have made ?

I've tried to resync your repo locally by rebasing the code. 
I ended up having conflicts in `app/src/main/java/free/rm/skytube/gui/businessobjects/adapters/GridViewHolder.java`. I only chose your modifications, and had other issues with private variables being accessed. So there will be a few issues with resyncing.
I finally got an APK with temporary fixes for the test, and it is working very well.
It only seems to conflict with the video blocker sometimes.
Would it also be possible to implement a video queue to queue videos for playing ?

Thanks for the hard work !

**Comment by snaggen** [comment]
What is the status if chromecast support? Is there an ETA for this? I would really like to throw out the regular youtube app and use SkyTube, but chromecast is a must have for me. 
I get the impression that it is mostly done, so I hope to see a PR for this soon... and if you need beta testers, just make an apk available and I will help out with testing and reporting.

**Comment by atomjack** [comment]
Hey @snaggen, I just pushed a PR a few days ago: https://github.com/ram-on/SkyTube/pull/365

Would you be able to compile and run it yourself, or do you need an APK?

**Comment by atomjack** [comment]
@aancel You shouldn't need to do any rebasing yourself. If there are any conflicts I will fix them when it comes time to merge.

I'd like to implemented a queue, but I've been having trouble figuring out how to implement the UI for it. LIke, how would you access the queue? I'd love to hear any ideas you might have.

**Comment by ram-on** [comment]
@snaggen Pls find attached a beta version of SkyTube which supports Chromecast.  We would appreciate if you report any issues noted.

[SkyTube-Extra-2.91 BETA.apk.zip](https://github.com/ram-on/SkyTube/files/2435336/SkyTube-Extra-2.91.BETA.apk.zip)

**Comment by snaggen** [comment]
Will test it and report any issues.

**Comment by snaggen** [comment]
After doing some simple tests, it seems to work great for playing clips on the chromecast! So this looks promising, and I will try to use it as my main youtube+chromecast player to really test it. 
One thing I noticed, was the lack of play queue support. I don't know if that is planned in a future release, but it is a really useful feature to be able to easily queue up a bunch of clips and be able to watch an hour without having to fiddle with the phone. And I like the way the regular youtube app handles this, that when you click on a clip when connected to a chromecast you get two options Play or Queue. 
Anyway, great job on this!

**Comment by atomjack** [comment]
I'll see if I can try to add queuing soon, maybe even before it's merged. Changing it so that tapping on a video while already playing a video shows a popup to either play (and I assume clear any queue) immediately or add it to the end of the queue is definitely the way to go. But then there's actually accessing the queue (to edit it, or skip to a different video in it). Maybe something as simple as in the options menu, a "Queue" item? 

The thing is, it would probably be a good idea to integrate this with playback on the device itself, which is actually something I've attempted, although I ran into some real problems with it when I tried it. But if @ram-on doesn't object, I could try to go this route with just the Chromecast functionality (i.e. you would only see the Queue options menu item if you were playing something on Chromecast).

**Comment by aancel** [comment]
@atomjack The rebase I did was just as a test to be able to build the apk, with the recent fixes on youtube videos.

Regarding to the queue, your comment is the way the official youtube application works:
> I'll see if I can try to add queuing soon, maybe even before it's merged. Changing it so that tapping on a video while already playing a video shows a popup to either play (and I assume clear any queue) immediately or add it to the end of the queue is definitely the way to go.

The menu item is also a good idea. Anyway as of the build I made, this is really a nice feature to have in the application.
Thanks again for the hard work ! :+1:

**Comment by snaggen** [comment]
Well, the comment is not really how the official youtube channel works, there is a slight difference. @atomjack writes "while already playing". This would mean that you would have to start playing something to be able to queue things, while the official youtube app works so that you get the popup _when you are connected_ to the chromecast. That way, it is possible to connect, queue up a lot of clips, then press play and watch. So I think that for a popup solution, that would be the preferred. 
However, having a menu item will probably work fine and is probably less work.

**Comment by ram-on** [comment]
I like the idea of having the "Queue" option within the video's option popup menu.

**Comment by atomjack** [comment]
I think a combined approach might work. Assuming you're connected to a chromecast, but nothing is yet playing, and nothing is in the queue, tapping on a video will start playing it. However, a video's options menu could also have an "Add to Queue" item, so you could add videos that way before actually starting playback. And also, come to think of it, doing it this way should probably show the mini controller right away (you won't be able to drag it up yet, though), so you can then choose to start playback once you're done adding videos to the queue.

Once you have at least one video in the queue (regardless of whether or not something is playing), tapping a video could show a popup with "play" and "add to queue" options. One question is how to handle selecting "play" - should it clear the queue and start playing that video? Or maybe just only play that video, leaving the queue alone (this might be kinda complicated to implement though)? Or maybe adding it to the end of the queue and immediately playing that video? The last would probably be easiest to implement.

The main options menu (in the title bar) could then have a "Queue" item that shows all the videos in the queue, allowing you to reorder/remove, or skip to another video, etc.

Just some ideas I'm having as I'm thinking of this. I'm loving your ideas though, please let me know what you think!

**Comment by atomjack** [comment]
I started to see if I could add queue support but it's going to be quite a bit of work, and I've been pretty busy lately. I'd like to push that off and hopefully get this merged before then. 

@ram-on, I also just pushed an update to the Chromecast branch adding some documentation to all the classes that were added by this branch.

**Comment by gzsombor** [comment]
This was actually merged a couple of days ago - [commit](https://github.com/ram-on/SkyTube/commit/160f97b0518c65003b069979fb3aa55bdd454d76)
