### ISSUE TITLE
Where do downloaded videos get stored?

### ISSUE THREAD

**Issue by mvglasow** [ram-on/SkyTube#278]
Where does SkyTube store downloaded videos? I couldn’t find any information on that, but I believe it needs to be documented somewhere.

**Comment by ram-on** [comment]
Hi @mvglasow, videos are downloaded to your Downloads folder (on your external storage space - such as your SD card).  Just use a File Manager (such as Android's Files app or F-Droid's Amaze), then tap on the Downloads section:  the downloaded videos should be there.

**Comment by atomjack** [comment]
FYI, on my Nexus 5, the downloads were put into the Movies folder of my sdcard. We're not specifying the exact folder they should be stored in; we're just asking Android to give us the path to the external storage public directory. [Here's](https://developer.android.com/reference/android/os/Environment.html#getExternalStoragePublicDirectory(java.lang.String)) the documentation for what we're using to get the path from. It states that it "Get(s) a top-level shared/external storage directory for placing files of a particular type.", and since the files are mp4, that explains why it's being stored in my 'Movies' folder. You might have to search around for the files, but they should be in your sdcard somewhere.

**Comment by ginsterbusch** [comment]
Well .. I havent found it yet. It would VERY helpful to actually be able to SET the download folder, not just search the whole bloody phone for wherever the app might have has hidden the downloaded file. X(

cu, w0lf.

**Comment by atomjack** [comment]
I recently added a feature to set the download folder, in #498. @gzsombor can you close this?

**Comment by gzsombor** [comment]
Sure, and we are under less than 100 issues.
