### ISSUE TITLE
Optionally save last playback position and watching history

### ISSUE THREAD

**Issue by vsudakov** [ram-on/SkyTube#286]
1. How about to have an option to save last playback position for each video?
This is very helpful when you watch a long movie time to time. Currently people have to seek the last playback position every time when they continue to watch that movie.

2. To keep history of watched videos?
For example, when I watch videos of the same channel - I don't remember which videos I've already watched in past... So, I spend some time to find ones which I haven't watched yet.
In my opinion, watched videos should be indicated somehow among other videos of the same channel.

That would be great to have an option to import/export those Last playback positions AND history along with subscriptions and bookmarks.

Thank to Ramon and all contributors for this Great App!

**Comment by atomjack** [comment]
That's a great idea. It would also be cool to, for instance, be able to switch between showing all videos and only showing videos you haven't watched before.

**Comment by ildar** [comment]
👍

**Comment by vsudakov** [comment]
@atomjack what you described - sounds great =)

**Comment by ram-on** [comment]
@atomjack I agree with all points.

I would also add (similar to the search feature) an option in the preferences to clear all video history and to disable logging of videos.  It would be nice if these are placed under a (separate) privacy (preference) section (together with the "Disable search history" option).

**Comment by atomjack** [comment]
@ram-on Sounds good. What should the default be, to save history or not?

**Comment by ram-on** [comment]
@atomjack By default the app should save the history.

**Comment by atomjack** [comment]
@ram-on Can you clue me in to how you created the preference icons (for video player, blocked channels, etc)? Trying to use a padlock outline one from Image Asset Clip Art but having trouble getting the color to match up.

**Comment by ram-on** [comment]
Choose "Action Bar and Tab Icons" and then select:
* Preference icon padding:  15%
* Theme:  CUSTOM
* Custom color:  263238 (equivalent to @color/colorPrimary)

**Comment by ram-on** [comment]
Hello Chris.  I really like the red-bottom progress bar! In fact I'm suggesting that instead of the red triangle, we just use the (full) progress to indicate that the video was fully played (just for the sake of consistency).

As for the settings, can you add an option to clear all history (only)?

Regarding that bug: when I've written the BackButtonActivity, I've jotted down this following comment:  `When inheriting from this class, do NOT forget to edit the AndroidManifest.xml and set the activity's style to @style/NoActionBarActivityTheme`.  To be honest I've forgot why this is needed - However when I was analyzing `YouTubePlayerActivity` I've noted the following code:
```java
if (useDefaultPlayer) {
	setTheme(R.style.NoActionBarActivityTheme);
}
```
which means that `YouTubePlayerV2Fragment` is using the `NoActionBarActivityTheme` theme... I suspect the reason why `YouTubePlayerFragment` is not correctly handling the on back button event.

In any case, can't we just override the `onDestroy()`?

**Comment by atomjack** [comment]
@ram-on Awesome, thanks for the input. I've done away with the red triangle and it will now just show the red bar at 100% width when a video is watched. And I add clear all history to the Privacy Preference screen.

I don't really think the Theme has much to do with it (as far as I can tell), however when I change the Activity to always use the NoActionBarActivityTheme, using the Legacy player crashes the app. I noticed the Activity by default uses the VideoPlayerActivityTheme theme (so, that theme is used when you use the legacy player). One interesting thing is that it looks like `onOptionsItemSelected()` *does* work, when using the Legacy player, but `onBackPressed()` does not. I'll do some more googling to see what I can figure out.

We can't really use `onDestroy()` to save the playback status as onDestroy gets called well after the Player Activity goes away and returns to the video grid, so the watched status (red bar) on the video you just played doesn't get updated. When you tap on a GridViewHolder (for a particular video), VideoGridAdapter saves a reference to the GridViewHolder you just tapped, then when BaseVideosGridFragment resumes, it tells that GridViewHolder to refresh itself (via VideoGridAdapter), so that the status gets updated. But this happens before `YouTubePlayerActivity.onDestroy()` gets called, so it doesn't update. It works fine when using `onBackPressed()` and `onOptionsItemSelected()`, though.

**Comment by atomjack** [comment]
@ram-on I figured it out. `MediaControllerEx` is overriding `dispatchKeyEvent`, and finishing the Activity when the Back button is pressed. I've updated it to have a reference to the Fragment (actually, an Interface I created that both Player Fragments implement) so it can tell the Fragment to stop playing the video and save its position (if needed). I'll have a PR up for your review soon.

**Comment by ram-on** [comment]
Done as per PR #293
