### ISSUE TITLE
Permissions, privacy and key limits.

### ISSUE THREAD

**Issue by cenotore** [ram-on/SkyTube#304]
I have been using your application for a very long time and I really liked it. **I especially liked that it did not require any permissions at all, except for access to the Internet**. I knew for sure that it will not read the data of my flash card and will not send my photos to anyone.

In one of the versions you added a request for permission to access the flash card. This behavior is not acceptable for me, so I just patched your application and removed it. Worked fine and I was happy.

But it seems that the old keys were once more rotten and I had to upgrade. I downloaded latest version from f-droid and stripped out any permissions except internet access.

First, I get the application crash when it starts. Error message:

```
W/System.err(  626): java.lang.SecurityException: ConnectivityService: Neither user 10227 nor current process has android.permission.ACCESS_NETWORK_STATE.
W/System.err(  626):    at android.app.ContextImpl.enforce(ContextImpl.java:1781)
W/System.err(  626):    at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1810)
W/System.err(  626):    at com.android.server.ConnectivityService.enforceAccessPermission(ConnectivityService.java:2331)
W/System.err(  626):    at com.android.server.ConnectivityService.getNetworkInfo(ConnectivityService.java:1236)
```

I delete this perm, because through it you can read the identification of the device and networks. Please remove it. Early versions of the application worked great without it.

But then I saw this:

```
E/GetYouTubeVideoBySearch( 1712): {
E/GetYouTubeVideoBySearch( 1712):   "code": 403,
E/GetYouTubeVideoBySearch( 1712):   "errors": [
E/GetYouTubeVideoBySearch( 1712):     {
E/GetYouTubeVideoBySearch( 1712):       "domain": "usageLimits",
E/GetYouTubeVideoBySearch( 1712):       "message": "The Android package name and signing-certificate fingerprint, free.rm.skytube.oss and ***********, do not match the app restrictions configured on your API key. Please use the API Console to update your key restrictions.",
E/GetYouTubeVideoBySearch( 1712):       "reason": "ipRefererBlocked",
E/GetYouTubeVideoBySearch( 1712):       "extendedHelp": "https://console.developers.google.com/apis/credentials"
E/GetYouTubeVideoBySearch( 1712):     }
E/GetYouTubeVideoBySearch( 1712):   ],
E/GetYouTubeVideoBySearch( 1712):   "message": "The Android package name and signing-certificate fingerprint, free.rm.skytube.oss and ***********, do not match the app restrictions configured on your API key. Please use the API Console to update your key restrictions."
```

Obviously, my re-assembly can not work with this. I also do not understand how to get my key. I do not have a Google Account, because it is attached to a phone number, so registration is not possible for me.

So far I can not use your application any more. Please do something about it.

In addition. This list of addresses was found in a binary from a f-droid:

```
http://169.254.169.254
http://google.com/
http://skytube-app.com
http://skytube-app.com/credits.html
http://www.w3.org/2000/xmlns/
https://accounts.google.com
https://accounts.google.com/o/oauth2/auth
https://accounts.google.com/o/oauth2/token
https://api-v2.soundcloud.com/charts?genre=soundcloud:genres:all-music&client_id=
https://api-v2.soundcloud.com/tracks/
https://api-v2.soundcloud.com/users/
https://api.github.com/repos/ram-on/SkyTube/releases/latest
https://api.soundcloud.com/i1/tracks/
https://api.soundcloud.com/playlists/
https://api.soundcloud.com/users/
https://developers.google.com/accounts/docs/application-default-credentials
https://www.google.com
https://www.googleapis.com/
https://www.googleapis.com/auth/youtube
https://www.googleapis.com/auth/youtube.force-ssl
https://www.googleapis.com/auth/youtube.readonly
https://www.googleapis.com/auth/youtube.upload
https://www.googleapis.com/auth/youtubepartner
https://www.googleapis.com/auth/youtubepartner-channel-audit
https://www.googleapis.com/batch
https://www.googleapis.com/oauth2/v1/certs
https://www.googleapis.com/youtube/v3/
https://www.youtube.com/channel/
https://www.youtube.com/embed/
https://www.youtube.com/feeds/videos.xml?channel_id=
https://www.youtube.com/get_video_info?video_id=
https://www.youtube.com/watch?v=
https://youtu.be/%s
https://youtube.com
```

My paranoia does not understand why the application needs access to addresses that it should not seem to have access to. For example google.com, api.soundcloud.com or even api.github.com, this is not related to youtube! You even have links with the http prefix, not https!

**Comment by ram-on** [comment]
Hi @cenotore.  I completely understand your "paranoia" as this is the whole reason why this app was written in the first place.

WRITE_EXTERNAL_STORAGE permission is used when:
1. when user wants to download a video or a video thumbnail.
1. when user wants to import or export the app's databases (such as subscriptions).

If you have a recent one (Android 6.0+) you can actually disable app's permissions.  Refer to [this article](https://support.google.com/googleplay/answer/6270602?hl=en) (refer to the Turn permissions on or off section).  Obviously, when the WRITE_EXTERNAL_STORAGE is disabled, the above features are not available.

As for the URLs noted above:  SkyTube makes use of [extractor library](https://github.com/TeamNewPipe/NewPipeExtractor).  This library is used to get the MPEG-4/3GPP/...etc URL for a given video.  This library was recently extended to also support other services other than YouTube such as Sound Cloud and this is hence why you got that URL.  This app never communicates with Sound Cloud as this goes beyond the app's scope.

As for github.com:  this feature is only required for SkyTube Extra.  SkyTube Extra communicates with github in order to check (at startup) if there are any updates available.  If there are, the app notifies the user and hence the app can updates itself (if the user wants to).  F-Droid's SkyTube (Vanilla version) does not communicate with github.com.

Regarding google.com:  my code never request any information from google.com.  Hence I did a quick search and found out that the "google.com" URL is being used by the above extractor library:
```
./app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java:513:        return Uri.parse("https://play.google.com/store/apps/details")
./app/src/test/java/us/shandian/giga/get/DownloadManagerImplTest.java:61:                "http://google.com/?q=how+to+google", file.getParent());
```
Both above google.com references appear to be harmless.

I hope this helps.
