### ISSUE TITLE
Gestures. More setting options.

### ISSUE THREAD

**Issue by DI555** [ram-on/SkyTube#397]
Please, add more options to gestures settings, it will greatly improove playing videos!

1. Swap between 'Sound' and 'Brigtness' gestures zones (swap left and right zones) option.
 Possibility to be set 'Sound' on right and 'Brightness' on left.
2. Settings of step (in %) of 'Sound' and 'Brightness' would greatly improve them also!
( now they're fixed to 6% for 'Sound' and 1% for 'Brightness' )
3. Double tap on right and left zones - rewinds forward and backward for X sec. With sets of each X.
4. Option to set step (in seconds) for rewinds with touch-and-drag-left/right gesture.
(now it's fixed with only 1 sec.)

**Comment by avently** [comment]
@DI555 
I made the swipe gestures and this is what I think about your suggestions.
1. For some reason @ram-on changed the original order of gestures: brightness was on the left side and volume on the right side, see
https://github.com/ram-on/SkyTube/commit/bd2b8495942a84f1d4495aec043bcd072e05fd3d
It's one of the most uncomfortable thing I met in the app because all apps I use have brightness on the left, volume on the right. I always use incorrect side in SkyTube, always. So, yes, I think the behavior should be changed back.
@ram-on, please, revert your commit. I can make a PR with configuration option if you really want the current gestures behaviour.
2. If I remember correctly it's not possible to make volume change in whatever percent you like. Because Android changes volume via built-in steps. The steps's count is 15, MX player has 15 steps too.
3. I don't like the idea. Because double tap to pause is so useful feature implemented here. When you need small adjustment to timeline you can make a little swipe. 
4. This is why I made the step small: to make small adjustment you mentioned in suggestion number 3.
When you want a big adjustment you probably want to use bottom timeline because it's easy than swiping for a long time.
But to be correct, step is not static. When you are watching a long video you can notice that swiping step changes dynamicaly. You can swipe a little bit and skip seconds but make a long swipe and this will skip a half of a video.

**Comment by gzsombor** [comment]
The brightness and volume side is confusing for me too, I always wondered if it's just me :wink: 
If you could implement a switch to change this, it would be awesome!

**Comment by gzsombor** [comment]
I've added a checkbox for switching the brightness and volume control, which seemed simple and useful.

**Comment by avently** [comment]
@gzsombor thanks, man. No need to support my local fork then

**Comment by gzsombor** [comment]
Why haven't you sent a pull request, if you had this feature?

**Comment by avently** [comment]
I don't have a checkbox in settings I just reverted a commit by ram-on where he changed behavior made by me. 
And since the creator of SkyTube did this I thought he will not accept PR related to this feature.

**Comment by gzsombor** [comment]
I see, sorry to hear. Next time, if you have a feature or bug fix, feel free to send patch(es) for it. 
SkyTube unfortunately currently is a one-man-show, run by me, which creates a lot of problem, for me, for the project, etc...
