### ISSUE TITLE
Change from progress dialogue to notification  when fetching videos

### ISSUE THREAD

**Issue by okan35** [ram-on/SkyTube#441]
As the title states, I was annoyed by the progress dialogue in the middle of app when fetching videos and it takes a lot of times when you have 1000 subscriptions. I know it disappears if you click but then you get no information about fetching process so I made notification for this. Because you still get  info about fetching process and you can also just close notification bar and when you wanna see you can see again which you can't achieve with progress dialogue.

It is compatible with pre oreo and post oreo versions.

So if it is ok, I can make a pull request.

**Comment by gzsombor** [comment]
Good idea, I'm similarly annoyed by this - even worse, if you happen to change the orientation of the screen, the re-fetching seems to be restarting.

**Comment by atomjack** [comment]
I started looking into this and it turns out I had written a Service that handles updating the Feeds tab, however @ram-on disabled it due to it not working properly, apparently. I don't remember the details but I will try to look into it and see if I can switch it over to using the Service instead of the AsyncTask (the Service will do an Android notification).

**Comment by okan35** [comment]
I couldn't reply before but if you don't wanna deal with it as I already did I can make a pull request this weekend.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by atomjack** [comment]
@okan35 Sure let's see what you came up with!

**Comment by okan35** [comment]
@gzsombor I believe you can just close this issue as it is committed.

**Comment by gzsombor** [comment]
Yes, I forgot to do it, thanks!
