### ISSUE TITLE
Document specific feature differences between SkyTube Extra and SkyTube

### ISSUE THREAD

**Issue by Gitoffthelawn** [ram-on/SkyTube#442]
Thank you for the excellent apps.

The readme indicates that SkyTube Extra "Contains extra features that are powered by non-OSS libraries".  What are these features, specifically?  This would also be great info to add to the readme.

Also, the readme indicates that SkyTube Extra has "Official YouTube player support".  Why is this desirable?  What functionality does this add?

**Comment by sbadux** [comment]
+1 :-)

**Comment by gzsombor** [comment]
I think, the readme clears enough:
* "Official YouTube player support" = powered by a closed-source, third-party library.
* SkyTube extra has Chromecast support - since recently.

Other than, they pretty similar.

Please open a pull request, if you think, more description would be beneficial, thank you!

**Comment by Gitoffthelawn** [comment]
@gzsombor Thank you for your reply.  Why would one want to use the closed-source third-party library?  What functionality/benefit does this add?

**Comment by narayaan** [comment]
Yeah as an enthusiastic skytube user, Iwas also wondering about this.

So the "extra feautures" could be reworded to "has Chromecast support as an extra feature"?
