### ISSUE TITLE
App crash on keyword search Skytube v2.95

### ISSUE THREAD

**Issue by expobar** [ram-on/SkyTube#446]
Steps taken:
1. Open app 
2. Search for any keyword
3. Not usually consistent but the issue gets triggered after 4-6 different keyword searches.

**Comment by expobar** [comment]
Logs captured

06-15 15:45:11.309 I/ActivityManager(1176): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity bnds=[843,930][1045,1212]} from uid 10025
06-15 15:45:11.339 I/ActivityManager(1176): Start proc 12438:free.rm.skytube.oss/u0a92 for activity free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity
06-15 15:45:11.342 E/.rm.skytube.os(12438): Not starting debugger since process cannot load the jdwp agent.
06-15 15:45:11.393 W/free.rm.skytube.oss(12438): type=1400 audit(0.0:676841): avc: denied { read } for comm=45474C20496E6974 name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=15935 scontext=u:r:untrusted_app:s0:c92,c256,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
06-15 15:45:11.588 I/ActivityManager(1176): Displayed free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity: +271ms
06-15 15:45:11.748 W/SurfaceFlinger(617): Attempting to set client state on removed layer: Splash Screen free.rm.skytube.oss#0
06-15 15:45:11.748 W/SurfaceFlinger(617): Attempting to destroy on removed layer: Splash Screen free.rm.skytube.oss#0
06-15 15:45:11.863 W/SurfaceFlinger(617): Attempting to set client state on removed layer: Surface(name=AppWindowToken{620c0d token=Token{f9b56a4 ActivityRecord{1cd6137 u0 free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity t1623}}})/@0x9531a28 - animation-leash#0
06-15 15:45:11.863 W/SurfaceFlinger(617): Attempting to destroy on removed layer: Surface(name=AppWindowToken{620c0d token=Token{f9b56a4 ActivityRecord{1cd6137 u0 free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity t1623}}})/@0x9531a28 - animation-leash#0
06-15 15:45:23.688 E/AndroidRuntime(12438): Process: free.rm.skytube.oss, PID: 12438
06-15 15:45:23.691 W/ActivityManager(1176):   Force finishing activity free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity
06-15 15:45:23.745 W/InputDispatcher(1176): channel 'fb127d free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
06-15 15:45:23.745 E/InputDispatcher(1176): channel 'fb127d free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-15 15:45:23.746 I/ActivityManager(1176): Process free.rm.skytube.oss (pid 12438) has died: fore TOP 
06-15 15:45:23.746 I/WindowManager(1176): WIN DEATH: Window{fb127d u0 free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity}
06-15 15:45:23.746 W/InputDispatcher(1176): Attempted to unregister already unregistered input channel 'fb127d free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity (server)'
06-15 15:45:23.750 W/SurfaceFlinger(617): Attempting to set client state on removed layer: free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity#0
06-15 15:45:23.750 W/SurfaceFlinger(617): Attempting to destroy on removed layer: free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity#0
06-15 15:45:24.764 I/ActivityManager(1176): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity} from uid 10025
06-15 15:45:24.784 I/ActivityManager(1176): Start proc 12478:free.rm.skytube.oss/u0a92 for activity free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity
06-15 15:45:24.786 E/.rm.skytube.os(12478): Not starting debugger since process cannot load the jdwp agent.
06-15 15:45:24.836 W/free.rm.skytube.oss(12478): type=1400 audit(0.0:676842): avc: denied { read } for comm=45474C20496E6974 name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=15935 scontext=u:r:untrusted_app:s0:c92,c256,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
06-15 15:45:25.024 I/ActivityManager(1176): Displayed free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity: +256ms
06-15 15:45:25.183 W/SurfaceFlinger(617): Attempting to set client state on removed layer: Splash Screen free.rm.skytube.oss#0
06-15 15:45:25.183 W/SurfaceFlinger(617): Attempting to destroy on removed layer: Splash Screen free.rm.skytube.oss#0
06-15 15:45:25.999 W/SurfaceFlinger(617): Attempting to set client state on removed layer: free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity#0
06-15 15:45:25.999 W/SurfaceFlinger(617): Attempting to destroy on removed layer: free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity#0
06-15 15:45:26.003 W/SurfaceFlinger(617): Attempting to set client state on removed layer: free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity#0
06-15 15:45:26.003 W/SurfaceFlinger(617): Attempting to destroy on removed layer: free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity#0
06-15 15:45:27.142 W/SurfaceFlinger(617): Attempting to set client state on removed layer: Surface(name=AppWindowToken{a10163 token=Token{2ce1392 ActivityRecord{43e651d u0 free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity t1623}}})/@0xcdfe3b6 - animation-leash#0
06-15 15:45:27.142 W/SurfaceFlinger(617): Attempting to destroy on removed layer: Surface(name=AppWindowToken{a10163 token=Token{2ce1392 ActivityRecord{43e651d u0 free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity t1623}}})/@0xcdfe3b6 - animation-leash#0
06-15 15:45:28.427 W/SurfaceFlinger(617): Attempting to set client state on removed layer: free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity#0
06-15 15:45:28.427 W/SurfaceFlinger(617): Attempting to destroy on removed layer: free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity#0
06-15 15:45:28.431 W/SurfaceFlinger(617): Attempting to set client state on removed layer: free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity#0
06-15 15:45:28.432 W/SurfaceFlinger(617): Attempting to destroy on removed layer: free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity#0

**Comment by atomjack** [comment]
I've noticed this sometimes as well, it seems to happen when you've previously searched for something, then search for something else that starts with the same word - once you hit a space after that word, it crashes. I'll look into finding a better suggestions library and also redoing the colors of the dropdown.

**Comment by okan35** [comment]
I have been using autocompleteTextView for a long time, havent had such issues, would definitely suggest, not sure you would put it into menu but yeah would suggest it.

**Comment by atomjack** [comment]
I'm actually not noticing that anymore. It seems to be working just fine now. I have been working on some updates to it, including using white icons and text on a black background, and have something just about ready to go. I've also updated it so that when you first tap the search icon, it shows the 10 most recent searches you did, in the suggestions dropdown, and then once you type 2 or more characters it updates the suggestions appropriately. Here's a [video](https://imgur.com/a/P53030H). (When I typed in "ho", I then tapped the X next to the third suggestion, to show it deleting it). Feedback would be appreciated. 

Some technical notes: I had to alter the SearchHistoryTable to add a datetime column, so at first the list might not necessarily be correct for someone who has already been using the app and upgrades to this change. This change had to grab all the entries out of the table, drop the table, and re-create it with the new datetime column, then add the entries back in, each with the current datetime (I had to do it this way as sqlite doesn't allow adding a column to a table that uses a default datetime (of the current datetime)). Once a search is executed (either by typing it in or tapping one of the suggestions), the datetime for that search text gets updated.

**Comment by gzsombor** [comment]
You can create a new table, with a different name - maybe even SQLite supports a "insert NewTable(...) select ... from OldTable" like syntax - and use that in the future.
Otherwise, it looks neat :+1:

**Comment by atomjack** [comment]
@gzsombor Yeah, in order to do that I'd have to create a new class for the new table. It seemed easier just to use onUpgrade to do it.

Here's the [pull request](https://github.com/ram-on/SkyTube/pull/466). It also includes a few lambdas that replaced anonymous type declarations. Once you're happy with this PR I'd like to do another one replacing the rest of the anonymous type declarations with lambdas (now that we're using Java 8).

Also, do you have a timeline on when you're planning on releasing a new version, with all the merges (including my chromecast stuff)?

**Comment by gzsombor** [comment]
I see, I'm ok with moving to lambdas. I only had minor comment about the pull request, thanks!

About the timeline of a release - good question. Unfortunately I don't know how to do a release, apart from tagging the code in github. I could upload an APK to github to the release, but it will be signed by me, instead of @ram-on which would make the upgrade, for the users, who downloads an APK from github painful (I think, that would mean, they would have to uninstall the previous version). But I don't know, how F-Droid is triggered, or how to update the website. I asked @ram-on, if/when he could do a release, but haven't received a response yet.
 Personally, I would like to have a release ASAP, because I like the new features, and the bug fixes, and I think, I won't be alone, if more people could try it.

**Comment by expobar** [comment]
@gzsombor I'd be glad to try out the new release. This issue has been bugging me for months. Fortunately you guys built an awesome backup system so migrating to your signed apk wouldn't bother me personally, as I've done migrations many times in the past.

**Comment by atomjack** [comment]
@gzsombor Yeah, unfortunately you'll have to go through @ram-on to get it released properly, I think. Hopefully he can spare some time now and then to take care of that.

**Comment by gzsombor** [comment]
I hope, this is fixed in 2.96, please re-open, if you see it again.
