### ISSUE TITLE
No Content?

### ISSUE THREAD

**Issue by rusty-genius** [ram-on/SkyTube#544]
Hey Guys,

first of all, thanks for the great app. It really changed the way i use youtube :)
that being said, skytube doesn't show me my content anymore.
i can see my abonnements but i can't see the videos after i click on them
also my feed doesn't load any videos, except for one or two random videos every 3 days or so.

i already updated several versions but the problem still persists. did you get hold of the problem yet?

thanks again

**Comment by gzsombor** [comment]
The problem is well known, already discussed a couple of times - like #516, #479, #523 etc...
The source of this problem was the Youtube API key problem - the builtin keys were limited, and overused. The new version has an alternative system to communicate with Youtube, which circumvents the official API.
