### ISSUE TITLE
When using NewPipe backend, all videos in subscriptions have 0% likes

### ISSUE THREAD

**Issue by Gitoffthelawn** [ram-on/SkyTube#557]
When using the NewPipe backend, all videos in subscriptions have 0% likes (100% disliked), which causes them all to be blocked by the content filter (when enabled).

Tested with SkyTube v2.964

**Comment by AlexNetman** [comment]
@Gitoffthelawn What does it mean "NewPipe".  I thought - NewPipe is different app.

**Comment by gzsombor** [comment]
@AlexNetman : you can switch on the experimental "NewPipe" backend, which uses https://github.com/TeamNewPipe/NewPipeExtractor instead of the official Youtube API.

@Gitoffthelawn , interesting, I can't reproduce your exact problem -  I mean, in the subscription tab, I have some videos filtered out, due to low number of views, but the numbers seems to be legit. The only problem what I could reproduce is that this blocking also works on the 'Download' tab, which doesn't make any sense to me - if you have already downloaded something, you probably want to see it. And sometimes, downloaded videos doesn't have their Like/Dislike saved.

**Comment by gzsombor** [comment]
I haven't seen this issue, and the NewPipe backend received a lot's of improvement.

**Comment by Flashwalker** [comment]
Same zero shit
