### ISSUE TITLE
Search bar bug the app

### ISSUE THREAD

**Issue by Lunovox** [ram-on/SkyTube#585]
If do you search in more one time, the app will stop and run break. To return the search bar to run in app, I did need delete all conf and restart the app. (Did keep the "factory config".)

Sorry, if my english language is bad. I am brasilian, and I speak well only in native portuguese.

**Comment by gzsombor** [comment]
Sorry, I'm also not a native English speaker, so it's not entirely clear what do you do, what happens exactly. Could you please describe step-by-step, what you click, where you go, etc...
What is the version of your app? Is it the OSS version, or the SkyTube Extra? What is your Android version?

**Comment by Lunovox** [comment]
**what happens exactly?**

The app crashes if you search for a video a second time. (if search history is enabled)

**Describe step-by-step**

1. Go to the privacy session in the settings.
2. Uncheck "Disable Search History".
3. Restart the application.
4. Click on the "Search Video" button
5. Perform search of any video normally.
6. Click the "Search Video" button again. 

Do it will crash, with (or without) Internet, because of Searsh History.
If disable the resource of "Search History" will not crash.

**What is the version of your app?**

My Smartphone is um LG E470f with android OS version 4.1.2 kernel 3.4.0
The version of instaled Skytube is 2.964 (of 2019-09-09), downloaded per F-Droid per link [ https://f-droid.org/packages/free.rm.skytube.oss/ ] 

This time I tried to improve my English essay post with the help of google translate to improve your understanding of this crash.

**Comment by gzsombor** [comment]
Thanks for the detailed information, it's really helpful!
I think, this issue is the same as #548, which were fixed in 2.965, unfortunately F-Droid hasn't merged my update request yet (https://gitlab.com/fdroid/fdroiddata/merge_requests/5641 - this became stale, and the new one is still open: https://gitlab.com/fdroid/fdroiddata/merge_requests/5760 ) When they merge, new version will appear on F-Droid too, with this problem fixed.
