### ISSUE TITLE
The app not working

### ISSUE THREAD

**Issue by rex07** [ram-on/SkyTube#643]
The app not working probably sense the version 2.95!

https://i.imgur.com/Lb24dHs.png
  
The log

`
01-23 06:49:36.658 I/am_pss  (15114): [11663,11530,free.rm.skytube.oss,23596032,20529152,0,77213696,1,14,59]
01-23 06:50:20.789 I/am_set_resumed_activity(15114): [0,free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity,resumeTopActivityInnerLocked]
01-23 06:50:20.795 I/am_resume_activity(15114): [0,101091867,1031,free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity]
01-23 06:50:20.725 I/ActivityManager(15114): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity bnds=[624,1361][793,1548]} from uid 11212
01-23 06:50:21.048 I/sysui_multi_action(15114): [319,83,321,79,322,264,325,30939,757,761,758,9,759,4,806,free.rm.skytube.oss,871,free.rm.skytube.gui.activities.MainActivity,904,com.teslacoilsw.launcher,905,0,1320,8,1321,4]
01-23 06:50:23.177 E/GetFeaturedVideos(11663):       "message": "The Android package name and signing-certificate fingerprint, free.rm.skytube.oss and 4203BADF131390D9DC930E12AF1E8737E89DF935, do not match the app restrictions configured on your API key. Please use the API Console to update your key restrictions.",
01-23 06:50:23.177 E/GetFeaturedVideos(11663):   "message": "The Android package name and signing-certificate fingerprint, free.rm.skytube.oss and 4203BADF131390D9DC930E12AF1E8737E89DF935, do not match the app restrictions configured on your API key. Please use the API Console to update your key restrictions."
01-23 06:50:26.773 W/NotificationService(15114): Toast already killed. pkg=free.rm.skytube.oss callback=android.app.ITransientNotification$Stub$Proxy@253cd
01-23 06:50:27.072 I/am_pause_activity(15114): [0,101091867,free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity,userLeaving=true]
01-23 06:50:27.134 I/am_stop_activity(15114): [0,101091867,free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity]
01-23 06:50:27.343 W/SurfaceFlinger(397): Attempting to set client state on removed layer: free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity#0
01-23 06:50:27.343 W/SurfaceFlinger(397): Attempting to destroy on removed layer: free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity#0`

**Comment by tokenmath** [comment]
I have the same problem

**Comment by atomjack** [comment]
@gzsombor I noticed all my API keys were gone from the api developer console, perhaps yours are too? Once I created a new one the the app worked properly (using the non-newpipe backend)

**Comment by gzsombor** [comment]
@rex07 : it's unclear what you've tried to do, but it seems, that you try to use a Youtube API key, which hasn't configured to use from that build. Be aware, that since 2.96, the signing-certificate fingeprint was changed, and so all the used keys too.

@atomjack : I've only experienced that the default development, debug keys were expired, the newly  created keys are fine.

**Comment by jhorner6511** [comment]
Hello Everyone. I am neither a spokesperson nor a representative of SkyTube or NewPipe, however, I am here to inform you all that the reason why both apps are not working has nothing to do with the apps themselves. Unfortunately, YouTube/Google has updated their policies recently, along with their algorithms, and is now preventing such apps from scraping their videos. YouTube now requires that any app that scrapes its website for content, like SkyTube or NewPipe, they must now enter a reCAPTCHA to verify it's a human being that is scraping the content.

All respective developers of both apps are aware of the issue and are in the process of figuring out a workaround to Google's new algorithm. Please pay attention for any new updates and/or comments from the developers in the near future. On their behalf, we apologize for any inconvenience this has caused you.

**Comment by atomjack** [comment]
@jhorner6511 Do you have any source for this, about the reCAPTCHA?

The problems @rex07 is encountering are because the API key that he's using do not match the app's method signature. They have nothing to do with Google changing anything.

Another problem that cropped up has been causing problems viewing video streams, but this is due to the NewPipeExtractor, which is an Open Source library that SkyTube uses to figure out the url for a video, stopped working due to Google changing some stuff that broke NewPipeExtractor, however those have now been fixed (in NewPipeExtractor; see [here](https://github.com/TeamNewPipe/NewPipeExtractor/issues/241)). @gzsombor should be pushing out a new release which includes this fix on Sunday 1/26 or so.

I was able to change which version of the Extractor the app is using on my device, to use the version that has this fix, and I am now able to view streams again just fine.

**Comment by gzsombor** [comment]
I'm closing this issue, as it's about an API key misuse, not an app error.
