### ISSUE TITLE
(Bug) Does not load all videos

### ISSUE THREAD

**Issue by tokenmath** [ram-on/SkyTube#645]
It does not upload all videos from any channel or playlist. This has been happening for a long time

**Comment by gzsombor** [comment]
This is a known problem, because the Youtube API key limitations. There is a workaround, to use the new 'NewPipe' backend in the preferences, which  scrapes the html.
 In 2.969 this NewPipe backend is used for the subscription fetching, even if the NewPipe backend is not requested specially.
 It's unclear what's the problem in your case, please provide more information.
