### ISSUE TITLE
Force-closes on Start in Android 4.0

### ISSUE THREAD

**Issue by IzzySoft** [ram-on/SkyTube#659]
I've just installed Skytube on an old Cat Galactica X (running ICS/Android 4.0 and never got an update) I still had lying around here. Unfortunately the app force-closes right on start. Any idea what that could be? Tried Skytube Extra, same issue.

<details>
<summary>Logcat</summary>
<pre>I/ActivityManager(  178): Start proc free.rm.skytube.oss for activity free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity: pid=3440 uid=10064 gids
D/ConnectivityService(  178): onUidRulesChanged(uid=10064, uidRules=0)
E/AndroidRuntime( 3440): FATAL EXCEPTION: AsyncTask #4
E/AndroidRuntime( 3440): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 3440):    at android.os.AsyncTask$3.done(AsyncTask.java:278)
E/AndroidRuntime( 3440):    at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
E/AndroidRuntime( 3440):    at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
E/AndroidRuntime( 3440):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
E/AndroidRuntime( 3440):    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
E/AndroidRuntime( 3440):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E/AndroidRuntime( 3440):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E/AndroidRuntime( 3440):    at java.lang.Thread.run(Thread.java:856)
E/AndroidRuntime( 3440): Caused by: java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
E/AndroidRuntime( 3440):    at com.google.api.client.util.escape.CharEscapers.decodeUriPath(CharEscapers.java:110)
E/AndroidRuntime( 3440):    at com.google.api.client.http.GenericUrl.toPathParts(GenericUrl.java:594)
E/AndroidRuntime( 3440):    at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:200)
E/AndroidRuntime( 3440):    at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:177)
E/AndroidRuntime( 3440):    at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:126)
E/AndroidRuntime( 3440):    at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:109)
E/AndroidRuntime( 3440):    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequestUrl(AbstractGoogleClientRequest.java:395)
E/AndroidRuntime( 3440):    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:430)
E/AndroidRuntime( 3440):    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:549)
E/AndroidRuntime( 3440):    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:482)
E/AndroidRuntime( 3440):    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:599)
E/AndroidRuntime( 3440):    at free.rm.skytube.businessobjects.YouTube.GetFeaturedVideos.getNextVideos(GetFeaturedVideos.java:70)
E/AndroidRuntime( 3440):    at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.getNextVideos(GetYouTubeVideosTask.java:117)
E/AndroidRuntime( 3440):    at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.doInBackground(GetYouTubeVideosTask.java:94)
E/AndroidRuntime( 3440):    at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.doInBackground(GetYouTubeVideosTask.java:39)
E/AndroidRuntime( 3440):    at android.os.AsyncTask$2.call(AsyncTask.java:264)
E/AndroidRuntime( 3440):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
E/AndroidRuntime( 3440):    ... 4 more
W/ActivityManager(  178):   Force finishing activity free.rm.skytube.oss/free.rm.skytube.gui.activities.MainActivity</pre>
</details>

**Comment by gzsombor** [comment]
This issue is recently discovered by @atomjack in this comment: https://github.com/ram-on/SkyTube/issues/620#issuecomment-577304607
 It's unclear, which version of the google-api-client introduced that it needs API 19.

**Comment by IzzySoft** [comment]
That would be Kitkat (Android 4.4). But SkyTube claims to run on ICS (Android 4.0 (API 14) – and that old Tabbi has no newer Android :cry:

**Comment by Ligands** [comment]
To clarify, this issue means that SkyTube does effectively have a minimum API level of 19 _already_, as it is currently crashing immediately on ICS/Jellybean.

My tablet doesn't have a stable rom available for anything past Android 4.2, so this seemed to be the only option left for browsing YouTube- other FOSS alternatives require newer android versions, and even the official app for this android version doesn't work anymore. Any chance we could get some clarification on whether the issue identified in #620 is resolvable in any way, or if API 19 is now the new minimum?

(inb4 it's time to buy a new one: I know that it's old, but I really don't need to buy another tablet... just wanted to see if I could get some use out of this one, because I highly doubt I'll even be able to resell it anymore.)

**Comment by gzsombor** [comment]
I totally understand you - it would be much better, if the app could work on Android 4.x - as it claims, and as all it's dependencies claim. The problem, is that I don't know any simple solution to fix it, and maintain the fix for the future releases. It seems, that in the Google client, they don't want to fix it: https://github.com/googleapis/google-http-java-client/issues/926

**Comment by Ligands** [comment]
Thanks for the quick update! That's a shame, but good to know- not a lot you can do about API deprecations like this.

**Comment by gzsombor** [comment]
Of course, we can fork google-http-java-client, and fix it by our self, if [this patch](https://github.com/googleapis/google-http-java-client/pull/1014) is wont merged. It's doesn't look to be a big patch.

**Comment by gzsombor** [comment]
So, google-http-java-client doesnt want to support Android API < 19, which is sad, but somehow understandable position. I could fix this issue temporarily, but due to limitations on TLSv1.2 / TLSv1.1 support, this wont work till the end of the time. AFAIK:
- Android 4.0 doesn't support TLSv1.1 / TLSv1.2
- Android 4.1 - 4.4 supports, but a custom socket factory is needed to enable it.
So my idea is that the next release will support Android 4.0 - again - but after, the minimum required API version will be 19 - just like NewPipe, and the other dependencies are requiring it. Maybe, we could have an android-4.0-legacy branch, and if someone wants to develop for it, they can work on it freely.
