### ISSUE TITLE
Periodical Video Playback Error makes SkyTube impossible to use

### ISSUE THREAD

**Issue by free5lot** [ram-on/SkyTube#854]
**Short description**
It's impossibly to use SkyTube for me because every 10-20 minutes I have huge messagebox `Video Playback Error` after which the playback position is forgotten and video is closed.

**Description**
I tried to play a couple of videos in SkyTube. Not streams, just usual uploaded videos.
The video gets interrupted at some point (after 10-20 minutes) and I see a huge message with title `Video Playback Error` and the body - super long link to some google data (probably chunk that was impossible to get?). I have only one button: `CLOSE`. 

When I press `CLOSE` I get out of video, the position is not saved (and it's impossible the remeber it manually as messagebox is huge, 95% of the screen). So, I have to open the video again, scroll several times to find the place I was listening. And then again this messagebox and exit from the video happens.

It makes the use of SkyTube completely impossible for me and probably other users who just remove the app instead of making a bug-report here. So, the issue is critical, to my opinion, please address it.

NOTE: I have no issues playing these videos in Firefox browser on the phone on the same Android device.

**Solution**
I propose several things to be changed:

- If `Video Playback Error` ugly messagebox shows then it should **NEVER close video** nor **forget the playback position**. It's unacceptable.
- If video playback actually occurs (internet is slow or google server is choppy) - **just RETRY** instead of throwing messagebox. Retry 10 times, 10 minutes or infinitely, because what else does the user expect from the SkyTube? To show a huge messagebox and close video? I doubt it. The browser players just retries until it gets the data.
- If ugly messagebox will remain then add additional button `RETRY`, but I see no reason not to make automatic retries without user interruption.
- The messagebox should not have huge url of failed video chunk. How can user use it?

**Workarounds:**
None that I know.

**Other issues:**
I found a bunch of `Video Playback Error` issues, but they do not look related or at least not the same. And they are solved. Mine is not and happens in the latest version of SkyTube.

**Version**
Version: 2.975, from f-droid.

_Thanks for the FLOSS app anyway!_

**Comment by gzsombor** [comment]
Saving the actual state would be indeed a reasonable thing, before we close the activity after the error dialog closed.
Anyway, it's interesting, that you had this video playback error message after 10-20 minutes. I usually only get just in the beginning, I'm curious what could be the cause for this. Just a connection error? 
 Doing retry make sense, but the question is, what needs to be retried. The problem is that there are two blackish box: one, is the Youtube's servers (and your networking situation), the other is the video player component, which is a pretty complex beast. For example, I saw Video Playback Error, when there were some OpenGL/hardware problem due to switching between various apps, which all wanted play some media (I'm not sure the exact reason, as I can't reproduce it reliably, but when I saw, I had other video players in the background...). So for this kind of error, we need to restart the whole activity, I believe. For a broken connection,  either we just re-set the datasource url to force re-fetching the video, or we could ask for youtube, to get new urls (as these urls I think are time sensitive, after X minutes, they are not working).

**Comment by free5lot** [comment]
>I'm curious what could be the cause for this. Just a connection error?

Not sure about this particular case but connection error by google's fault is actually a quite common thing. If you use `youtube-dl` then once in a while you will see situations when getting some video's chunks failed and happened after several retries only. And it's google-server-specific issue because it happens with one video at exact day and does not happen with others videos (on other google-servers).
When you use browser you never notice this because html-page will make retries itself without any messages to user.

So, I'm pretty sure retry should be used in most cases. Maybe there is such option for backend you are using.

>we could ask for youtube, to get new urls (as these urls I think are time sensitive, after X minutes, they are not working).

A long link I saw in messagebox had `&sparams=expire%2Cei%C` substring, but it may mean nothing.
Note: I was watching video with phone locked (actually was listening).
