### ISSUE TITLE
UI responsiveness question

### ISSUE THREAD

**Issue by brok85** [ram-on/SkyTube#88]
Dear SkyTube Developers,
I am implementing a hang-bug detection tool and I am analyzing SkyTube with it (master version commit number  3da671c). I found that the main thread of SkyTube frequently calls

`org.ocpsoft.prettytime.PrettyTime.<init>(PrettyTime.java:71)`

often, for example, when the main activity is resumed. When this happens, a hang of about 0.5 seconds is generated. The following extracts of stack trace highlights where is the source of the hang problem:

`
...
org.ocpsoft.prettytime.PrettyTime.<init>(PrettyTime.java:71), free.rm.skytube.businessobjects.PrettyTimeEx.<init>(PrettyTimeEx.java:0), free.rm.skytube.businessobjects.YouTubeVideo.getPublishDatePretty(YouTubeVideo.java:195), free.rm.skytube.gui.businessobjects.GridViewHolder.updateViewsData(GridViewHolder.java:101), free.rm.skytube.gui.businessobjects.GridViewHolder.updateInfo(GridViewHolder.java:87), free.rm.skytube.gui.businessobjects.VideoGridAdapter.onBindViewHolder(VideoGridAdapter.java:171), free.rm.skytube.gui.businessobjects.VideoGridAdapter.onBindViewHolder(VideoGridAdapter.java:40)
...
`

The Android documentation states that heavy functions should not be executed on the UI thread. As a result, moving the execution of the above functions off the main thread may lead to higher responsiveness of the app.

Do you think that the responsiveness of the app would improve by executing the above API in a background thread rather than on the main thread?

Thanks for any information,
I hope I can help improve SkyTube

**Comment by ram-on** [comment]
@brok85 Hi, Thank you for your input.  In fact, I've recently noted that the app is a bit lagging/stuttering when the videos grid is scrolled.

> Do you think that the responsiveness of the app would improve by executing the above API in a background thread rather than on the main thread?

I agree completely.

> I am implementing a hang-bug detection tool and I am analyzing SkyTube with it

I would love to get a copy of this tool!  It would be really useful.

**Comment by atomjack** [comment]
@ram-on I just implemented a fix for this, that sets the pretty format of the publish date (for both videos and comments) in a background thread (via AsyncTaskParallel). You can see it [here](https://github.com/atomjack/SkyTube/commit/8ab71fa03812ea77becde6d206a00310ee415050). Let me know what you think and if it looks ok, I'll do a PR.

**Comment by brok85** [comment]
Thanks a lot for the feedback!

I am still working on the tool so your feedback is very important. 

The fix looks good to me! I can test the new version again and tell you how it goes if you like.

**Comment by ram-on** [comment]
@atomjack While I agree with your fix, the main issue here is with the Videos Grid fragment.  Perhaps you take a look into that fragment as well?

**Comment by brok85** [comment]
I made some preliminary test with the new version and those hangs do not occur anymore. I will keep testing however to see if I can find anything else.

**Comment by atomjack** [comment]
@ram-on I agree that the main issue is the Videos Grid fragment, however @brok85 found that that call to format the date was hanging a bit (and the call to `YouTubeVideo.getPublishDatePretty` is happening in `GridViewHolder.java`, so it's being called for each and every video that is displayed in the grid). Do you think you could pull down my branch and try it out on your tablet to check if you see some improved performance? It's possible you are only seeing performance issues now since the earlier version of SkyTube was only loading one Grid at a time, whereas the ViewPager loads several of them, and with the Subscriptions & Bookmarks tab, we now have at least 2, and up to 3, grids being filled out with videos. (And remember, you can change the number of pages that are being filled out by changing the call to `viewPager.setOffscreenPageLimit()` - it is currently set to load 3 pages.)

It sounds like @brok85 's hang-bug detection tool could hopefully track down any other performance problems we're having so maybe we can wait to see if any more are found with it. @brok85, thanks for your help!

**Comment by ram-on** [comment]
@atomjack Yes I'll try out your code tomorrow and will let you know how it went.

**Comment by ram-on** [comment]
@brok85 any updates regarding your tool?

**Comment by ram-on** [comment]
Closed due to lack of feedback.
