### ISSUE TITLE
Can I use the YouTube API to get my subscriptions into SkyTube?

### ISSUE THREAD

**Issue by Poomex** [ram-on/SkyTube#98]
Is this even possible? I'm not a programmer, but since you've added the option I have created an API key and set it up in SkyTube. However I'm not really entirely sure what this is for. Sorry for the noob question. :)

**Comment by ram-on** [comment]
Hello @Poomex 

- In order to communicate with YouTube, the SkyTube has been assigned a 'key' by Google.
- However, each key can only be used X amount of times daily.
- Lately SkyTube has become quite popular and we are exceeding the key limits.  When the limits are exceeded users cannot use the app (i.e. SkyTube will be unable to communicate with YouTube).
- By using your own private key, you'll be sure that the app is always available for you.

**Comment by Poomex** [comment]
I see, so this has nothing to do with subscriptions, it just takes the load off your API key. I'm going to use my own to lighten the burden, beacuse SkyTube is easily the best FOSS YouTube app there is and I'd like to support it in some way. Thanks!

**Comment by ram-on** [comment]
Thanks for the support.
